### PR TITLE
(MAINT) Add ecdsa-sha2 key types

### PR DESCRIPTION
**Pull request by scotje**

### CODE REVIEW

**Comment by genebean** [comment]
Will you please rebase after #16 is merged? Doing so should get us real tests.

**Comment by genebean** [comment]
#16 has been merged

**Comment by scotje** [comment]
Looks like the CI is passing now! 🎉

**Review by genebean — APPROVED** [review]

**Comment by scotje** [comment]
I don't have merge bits on this repo, so you can merge whenever you want @genebean

**Pull request merged**
